Repository AY2425S1-CS2103T-W11-1a/tp, pull requests merged in 2024-11, with the labels that each got.

#77 Nric indexing
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/LogCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/LogCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/LogCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalNrics.java
Labels: type.Story, priority.High

#102 Add to Developer Guide
  docs/DevOps.md
  docs/DeveloperGuide.md
Labels: type.Task, severity.Medium

#105 Add acknowledgements and additional test cases to DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/dominic-khoo.png
Labels: type.Task

#93 Fix help window formatting
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug

#95 Fix remark CLI message
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Labels: type.Bug, priority.Medium

#94 Fix duplicate nric
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, severity.Medium

#120 Fix bugs detected during alpha testing
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, alpha-bug

#114 Update UG to match current iteration of features
  docs/UserGuide.md
  docs/images/ViewWindow.png
  docs/index.md
Labels: priority.High

#115 Add appointment details to view window of ViewCommand
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/ui/ViewWindow.java
  src/main/resources/view/ViewWindow.fxml
Labels: type.Bug, alpha-bug

#124 Add triage command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/TriageCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TriageCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Triage.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/TriageCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/TriageCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TriageTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#132 Fix checkstyle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Triage.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TriageCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/TriageTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High, alpha-bug

#149 Add Address Unit tests
  src/test/java/seedu/address/model/person/AddressTest.java
Labels: type.Task

#199 Update UG with Triage Command
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High

#200 Update help window to include triage command
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High, severity.High

#203 UG, UI and HelpWindow Bug Fixes
  docs/UserGuide.md
  docs/images/HelpPage.png
  docs/images/Ui.png
  docs/images/ViewWindow.png
  docs/images/searchResult.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ViewWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/ViewWindow.fxml
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug, severity.High, alpha-bug

#209 Update DG, UG, Help Window
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, severity.High

#208 Fix usage messages
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/TriageCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: type.Bug, priority.High

#215 Fix find parser
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: priority.High, severity.Medium

#216 Update UG for PE-D bug fixes and edit triage
  docs/UserGuide.md
  docs/images/AppointmentPopup.png
  docs/images/HelpPage.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TriageCommand.java
Labels: type.Bug, priority.High, severity.High

#220 Fix triage command invalid input messages
  src/main/java/seedu/address/logic/parser/TriageCommandParser.java
Labels: type.Bug

#224 Fix view null pointers
  src/main/java/seedu/address/ui/ViewWindow.java
Labels: priority.High, severity.High

#225 Fix tag message
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.Medium
